project_name: gitlab-code-quality
builds:
  -
    main: ./cmd/gitlab-code-quality
    id: "gitlab-code-quality"
    binary: gitlab-code-quality
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  -
    maintainer: Marco Santos <me@marcopsantos.com>
    description: Gitlab code quality reporter
    homepage: https://github.com/LOQ9/gitlab-code-quality
    license: MIT
    formats:
    - deb
    - rpm
    - apk

archives:
  -
    format: binary

dockers:
  -
    id: gitlab-code-quality
    image_templates:
    - "ghcr.io/loq9/{{ .ProjectName }}:{{ .Tag }}"
    - "ghcr.io/loq9/{{ .ProjectName }}:latest"
    dockerfile: "Dockerfile.minimal"
    build_flag_templates:
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/LOQ9/gitlab-code-quality
    - --label=org.opencontainers.image.source=https://github.com/LOQ9/gitlab-code-quality
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
