FROM alpine:3.17

RUN apk update && \
  apk add --no-cache curl ca-certificates && \
  rm -rf /var/cache/apk/*

WORKDIR /app

ADD gitlab-reporter /app/gitlab-reporter
RUN chmod u+x /app/gitlab-reporter

# Start
ENTRYPOINT [ "/app/gitlab-reporter", "transform", "--detect-report", "--output-file", "gl-code-quality-report.json" ]