FROM alpine:3.16

RUN apk update && \
  apk add --no-cache curl ca-certificates && \
  rm -rf /var/cache/apk/*

WORKDIR /app

ADD gitlab-code-quality /app/gitlab-code-quality
RUN chmod u+x /app/gitlab-code-quality

# Start
ENTRYPOINT [ "/app/gitlab-code-quality", "transform", "--detect-report", "--output-file", "gl-code-quality-report.json" ]